name: cloud-storage

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud-storage
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5555:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7.4.1-alpine
    container_name: redis_local
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
    driver: local
